export const START_LOADING = "APP/START_LOADING";
export const FINISH_LOADING = "APP/FINISH_LOADING";
export const FINISH_REGISTER = "APP/FINISH_REGISTER";
export const SET_ERROR = "APP/SET_ERROR";
export const REMOVE_ERROR = "APP/REMOVE_ERROR";
export const SHOW_MESSAGE = "APP/SHOW_MESSAGE";
export const HIDE_MESSAGE = "APP/HIDE_MESSAGE";

export const GET_CURRENT_USER = "AUTH/GET_CURRENT_USER";
export const LOGIN = "AUTH/LOGIN";
export const LOGOUT = "AUTH/LOGOUT";
export const REGISTER = "AUTH/REGISTER";
export const FORGOT_PASSWORD = "AUTH/FORGOT_PASSWORD";
export const RESET_PASSWORD = "AUTH/RESET_PASSWORD";

export const LOAD_VOTING = "VOTING/LOAD_VOTING";
export const GET_VOTING_FROM_DB = "VOTING/GET_VOTING_FROM_DB";
export const GET_VOTING_FROM_CONTRACT = "VOTING/GET_VOTING_FROM_CONTRACT";
export const GETTING_VOTING_FAILED = "VOTING/GETTING_VOTING_FAILED";
export const UPDATE_VOTING = "VOTING/UPDATE_VOTING";
export const ARCHIVE_VOTING = "VOTING/ARCHIVE_VOTING";
export const START_VOTING = "VOTING/START_VOTING";
export const DELETE_VOTING = "VOTING/DELETE_VOTING";

export const LOAD_VOTINGS = "VOTINGS/LOAD_VOTINGS";
export const GETTING_VOTINGS_SUCCESS = "VOTINGS/GETTING_VOTINGS_SUCCESS";
export const GETTING_VOTINGS_FAILED = "VOTINGS/GETTING_VOTINGS_FAILED";
export const GET_ALL_VOTINGS = "VOTINGS/GET_ALL_VOTINGS";
export const GET_VOTINGS_BY_USER = "VOTINGS/GET_VOTINGS_BY_USER";
export const GET_ACTIVE_VOTINGS = "VOTINGS/GET_ACTIVE_VOTINGS";
