export const SHOW_ERROR = "APP/SHOW_ERROR";
export const HIDE_ERROR = "APP/HIDE_ERROR";
export const SHOW_MESSAGE = "APP/SHOW_MESSAGE";
export const HIDE_MESSAGE = "APP/HIDE_MESSAGE";
export const SET_ADMIN_TAB = "APP/SET_ADMIN_TAB";

export const SHOW_MODAL = "MODAL/SHOW_MODAL";
export const HIDE_MODAL = "MODAL/HIDE_MODAL";
export const MODAL_LOADING = "MODAL/MODAL_LOADING";
export const MODAL_LOADED = "MODAL/MODAL_LOADED";
export const SET_MODAL_RESULT = "MODAL/SET_MODAL_RESULT";
export const REMOVE_MODAL_RESULT = "MODAL/REMOVE_MODAL_RESULT";
export const SET_MODAL_ERROR = "MODAL/SET_MODAL_ERROR";
export const REMOVE_MODAL_ERROR = "MODAL/REMOVE_MODAL_ERROR";

export const PROFILE_LOADING = "PROFILE/PROFILE_LOADING";
export const PROFILE_LOADED = "PROFILE/PROFILE_LOADED";
export const GET_PROFILE = "PROFILE/GET_PROFILE";
export const LOGIN = "PROFILE/LOGIN";
export const LOGOUT = "PROFILE/LOGOUT";
export const REGISTER = "PROFILE/REGISTER";
export const FORGOT_PASSWORD = "PROFILE/FORGOT_PASSWORD";
export const RESET_PASSWORD = "PROFILE/RESET_PASSWORD";
export const UPDATE_PROFILE = "PROFILE/UPDATE_PROFILE";

export const VOTING_LOADING = "VOTING/VOTING_LOADING";
export const VOTING_LOADED = "VOTING/VOTING_LOADED";
export const GET_VOTING_FROM_DB = "VOTING/GET_VOTING_FROM_DB";
export const GET_VOTING_FROM_CONTRACT = "VOTING/GET_VOTING_FROM_CONTRACT";
export const CREATE_VOTING = "VOTING/CREATE_VOTING";
export const UPDATE_VOTING = "VOTING/UPDATE_VOTING";
export const ARCHIVE_VOTING = "VOTING/ARCHIVE_VOTING";
export const START_VOTING = "VOTING/START_VOTING";
export const DELETE_VOTING = "VOTING/DELETE_VOTING";

export const VOTINGS_LOADING = "VOTINGS/VOTINGS_LOADING";
export const VOTINGS_LOADED = "VOTINGS/VOTINGS_LOADED";
export const GET_ALL_VOTINGS = "VOTINGS/GET_ALL_VOTINGS";
export const GET_VOTINGS_BY_USER = "VOTINGS/GET_VOTINGS_BY_USER";
export const GET_ACTIVE_VOTINGS = "VOTINGS/GET_ACTIVE_VOTINGS";

export const USERS_LOADING = "USERS/USERS_LOADING";
export const USERS_LOADED = "USERS/USERS_LOADED";
export const GET_ALL_USERS = "USERS/GET_ALL_USERS";
export const DELETE_USERS = "USERS/DELETE_USERS";

export const USER_LOADING = "USER/USER_LOADING";
export const USER_LOADED = "USER/USER_LOADED";
export const CREATE_USER = "USER/CREATE_USER";
export const GET_USER = "USER/GET_USER";
export const UPDATE_USER = "USER/UPDATE_USER";
export const DELETE_USER = "USER/DELETE_USER";
